language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo bash scripts/install_deps.sh
  - sudo bash scripts/update_gcc.sh

script:
  - bash scripts/build_and_bundle.sh
  - cd insight
  - export VERSION=$(git rev-parse --short HEAD)
  - cd ..
  - wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  - chmod +x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage AppDir/Insight.desktop -bundle-non-qt-libs
  - bash scripts/copy_libs.sh
  - bash scripts/apply_patches.sh
  - bash scripts/purge_unwanted.sh
  - wget -O AppDir/AppRun https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64
  - chmod +x AppDir/AppRun
  - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
  - chmod +x appimagetool-x86_64.AppImage
  - ./appimagetool-x86_64.AppImage -g AppDir

after_success:
  - # curl --upload-file ./Insight-*-x86_64.AppImage "https://transfer.sh/Insight.AppImage" > ./one-upload
  - # echo "$(cat ./one-upload)" # this way we get a newline
  - # echo -n "$(cat ./one-upload)\\n" >> ./uploaded-to
  - bash scripts/upload.sh Insight-*-x86_64.AppImage *zsync

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
